export enum ETATPRODUCTION {
  ATTENTE = 'ATTENTE',

  PRODUCTION = 'PRODUCTION',

  VALIDATION = 'VALIDATION',

  COURRIER = 'COURRIER',

  VERIFICATION = 'VERIFICATION',

  TERMINER = 'TERMINER',
}
